
language: node_js

node_js:
 - "0.11"
 
before_install: npm install -g grunt-cli

install: npm install

before_script: grunt

deploy:
  provider: heroku
  api_key:
    secure: cWBEDgBTTa2vBA0NuXIUa44Am5xaC8+quTTJAeAe2WsO+cPaq1+GsmwFrdLzvGFVX2gFfh14u+IBc9HKbPvpPQ+wfyvqu3IECI+eGamuL4l+iwLsBVCLVKkbqCnRvN5BpHw7fcZTZplRtF1UDLohunYmY9YEPNz3q4sSyi/33EA=
  app: pagy-demo
  on:
    repo: samuelgrigolato/pagy
