
language: node_js

node_js:
 - "0.11"

before_install: npm install -g grunt-cli

install: npm install

before_script: grunt

deploy:
  provider: heroku
  api_key: 
    secure: hYiUEYCp7y557whUceZQp71cRpZ1LZABYI8liHH2oXlTTztN9Siix6x9cZV6MKvdorPbTqlT7SuQjboxPXtUZnUQpB076of7Rjigybdg7ZKS6rAOgmvgvoVm7t0QQiywztTHg+phIJEpId+mJXb0936MNUbMLSx3xRJUpZZY9Oc=
  app: pagy-demo
  on:
    repo: "samuelgrigolato/pagy"