// Generated by CoffeeScript 1.7.1
(function() {
  var main;

  main = new Main;

  test("square", function() {
    ok((main.square(3)) === 9, "square of 3 = 9");
    return ok((main.square(4)) === 16, "square of 4 = 16");
  });

}).call(this);

//# sourceMappingURL=pagy-0.1.tests.map
