// Generated by CoffeeScript 1.7.1
(function() {
  var Main;

  Main = (function() {
    function Main() {}

    Main.prototype.square = function(x) {
      return x * x;
    };

    return Main;

  })();

  window.onload = function() {
    var main;
    main = new Main;
    return console.log("The square of 5 is " + (main.square(5)));
  };

  window.Main = Main;

}).call(this);

//# sourceMappingURL=pagy-0.1.map
