// Generated by CoffeeScript 1.7.1
(function() {
  var main, square;

  square = function(x) {
    return x * x;
  };

  main = function() {
    return alert("The square of 5 is " + (square(5)) + "!");
  };

  window.onload = main;

}).call(this);

//# sourceMappingURL=pagy.map
